# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 悬崖不勒马的小站
subtitle: ''
description: 'The time you enjoy wasting is not wasted time!'
keywords: 
author: 悬崖不勒马
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://xuanyabulema.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: git
  repo: git@github.com:xuanyabulema/xuanyabulema.github.io.git
  branch: master
- type: baidu_url_submitter # 百度

# Local Search本地搜索
search:
  path: search.xml
  field: post
  content: true
  format: html

# 增加文章字数统计及阅读时常功能
symbols_count_time:
  symbols: false
  time: true
  total_symbols: false
  total_time: false
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."

# 为博客加上妹子
live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  log: false
  model:
    use: live2d-widget-model-hijiki
  display:
    position: left
    width: 150
    height: 300
  mobile:
    show: false

# 让Hexo博客支持emoji显示
# 首先卸载hexo-renderer-marked 安装hexo-renderer-markdown-it和markdown-it-emoji
# npm un hexo-renderer-marked --save
# npm i hexo-renderer-markdown-it markdown-it-emoji -S
# 更改站点的markdown配置
# markdown:
#   render:
#     html: true
#     xhtmlOut: false
#     breaks: true
#     linkify: true
#     typographer: false # 改为false解决“英文的引号会被渲染为中文的引号”的问题
#     quotes: '“”‘’'
#   plugins:
#     - markdown-it-abbr
#     - markdown-it-footnote
#     - markdown-it-ins
#     - markdown-it-sub
#     - markdown-it-sup
#     - markdown-it-emoji
#   anchors:
#     level: 2
#     collisionSuffix: 'v'
#     permalink: true
#     permalinkClass: header-anchor
#     permalinkSymbol: ''

markdown_it_plus:
    highlight: true
    html: true
    xhtmlOut: true
    breaks: true
    langPrefix: 
    linkify: true
    typographer: false # 改为false解决“英文的引号会被渲染为中文的引号”的问题
    quotes: “”‘’
    pre_class: highlight


# 隐藏文章
hide_posts:
  # 可以改成其他你喜欢的名字
  filter: hidden
  # 指定你想要传递隐藏文章的位置，比如让所有隐藏文章在存档页面可见
  # 常见的位置有：index, tag, category, archive, sitemap, feed, etc.
  # 留空则默认全部隐藏
  public_generators: []
  # 为隐藏的文章添加 noindex meta 标签，阻止搜索引擎收录
  noindex: true

# 让Google搜索到搭建在Github Pages上的博客
sitemap:
  path: 
    - sitemap.xml
    - sitemap.txt
  # template: ./sitemap_template.xml
  # template_txt: ./sitemap_template.txt
  rel: false
  tags: false
  categories: false


baidu_url_submit:
  count: 100 ## 提交最新的一个链接
  host: xuanyabulema.github.io ## 在百度站长平台中注册的域名
  token: JzhuvqPcIUDtOR8c ## 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址， 新链接会保存在此文本文档里
  # xz_appid: 'xxxxxx' ## 你的熊掌号 appid
  # xz_token: 'xxxxxx' ## 你的熊掌号 token
  # xz_count: 10 ## 从所有的提交的数据当中选取最新的10条,该数量跟你的熊掌号而定


